# OUTPUTS of the feature engineering notebook
**products_train_UK_representations.csv**
- This file contains 3 columns: `id`, `price`: numeric, and `representation`: a numeric vector of dimension 768, representing all the information of the products.

**sessions_UK_finalized_len2.csv**
- This file contains 52199 rows × 2 columns: `next_item`, `prev_items`
- Only keep the rows where the number of previous items purchased >= 2, if it's longer than 2, only keep the latest 2 items

**sessions_UK_finalized_len3.csv**
- This file contains 25615 rows × 2 columns: `next_item`, `prev_items`
- Only keep the rows where the number of previous items purchased >= 3, if it's longer than 3, only keep the latest 3 items

In [ ]:
df_UK_representations

              id  price                                     representation
0     B07PNBPVN1   3.75  [-0.21872417628765106, -0.2500726580619812, -0...
1     B0B45XQ6Q3   8.59  [-0.7130799889564514, -0.5445948839187622, -0....
2     B01CR9IRWY  16.00  [-0.8353576064109802, -0.6093693375587463, -0....
3     B077RCBS9C  36.98  [-0.8522624969482422, -0.5257986783981323, -0....
4     B088BMDXPD   7.99  [-0.8538389205932617, -0.47541171312332153, -0...
...          ...    ...                                                ...
6685  B00NBR70DO  13.22  [-0.9247933626174927, -0.5451830625534058, -0....
6686  B08HYPQ4VR  12.99  [-0.9244785308837891, -0.5655009150505066, -0....
6687  B09LR8NRL9   2.89  [-0.8537996411323547, -0.557623565196991, -0.9...
6688  B0987DMWKW  15.99  [-0.6583928465843201, -0.3460875451564789, -0....
6689  B08BHMLGSV  15.99  [-0.8860562443733215, -0.6518399715423584, -0....

[6690 rows x 3 columns]

In [ ]:
sessions_train_UK_filtered_len2

          next_item                prev_items
2090615  B0046U4CGS  [B01NCPFGQ3, B01N0U5UDH]
2090657  B07QS8M6W4  [B08HLVKVWR, B00I874D4Q]
2090669  B094VMJK1G  [B094VLF9QV, B0B24Z4D3V]
2090679  B07YQ1XM6J  [B0177HKHQK, B01HQHGIBY]
2090729  B0B63T3HGD  [B09JXY17B6, B004PYD9QE]
...             ...                       ...
3272505  B0BKPXCVHZ  [B08B4T5ZWJ, B08B4T5ZWJ]
3272540  B08KS94WMW  [B0BG912PV7, B09Z8C64DT]
3272591  B004AVB4UK  [B0BCLGK9DD, B00VP2SSFG]
3272609  B0BD96VGPW  [B08L6RD61H, B07XTNBQ8G]
3272613  B07S6C1DZ6  [B07DYBV29C, B07DYBV29C]

[52199 rows x 2 columns]

In [ ]:
sessions_train_UK_filtered_len3

          next_item                            prev_items
2090615  B0046U4CGS  [B01NBMYWIN, B01NCPFGQ3, B01N0U5UDH]
2090729  B0B63T3HGD  [B09RQDZDF7, B09JXY17B6, B004PYD9QE]
2090735  B08FRDSKK8  [B082DYJF52, B08TWZD1H4, B082DYJF52]
2090744  B007EA03UQ  [B079KJLDF2, B08J4H9RSW, B074RCV4HQ]
2090798  B0838CF4T4  [B07PNL5STG, B07PNL5STG, B08KXPF5NK]
...             ...                                   ...
3272443  B07XLSHWP5  [B09F9QX6HB, B09XTTMJ8F, B09XTGBVF6]
3272449  B07SWQTPDZ  [B09Q3MSNJ8, B09Q3MRZ14, B08VF94DSV]
3272505  B0BKPXCVHZ  [B095BN6W33, B08B4T5ZWJ, B08B4T5ZWJ]
3272540  B08KS94WMW  [B09Z8C64DT, B0BG912PV7, B09Z8C64DT]
3272591  B004AVB4UK  [B00VP2SSFG, B0BCLGK9DD, B00VP2SSFG]

[25615 rows x 2 columns]

In [1]:
import pandas as pd
from transformers import BertTokenizer, BertModel
import torch

/Users/stoneman/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/stoneman/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (

In [4]:
df = pd.read_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/products_train.csv')

In [7]:
# find the rows where id is not unique
df[df.duplicated(subset=['id'], keep=False)].sort_values(by='id')

,id,locale,title,price,brand,color,size,model,material,author,desc
1420610,0007477155,ES,A Game of Thrones: The Story Continues: The bo...,54.01,Harper Collins Publ. UK,NaN,NaN,NaN,NaN,"Martin, George R.R.",NaN
1502753,0007477155,IT,A Game of Thrones: The Story Continues: The co...,74.11,Harper Collins Publ. UK,NaN,NaN,NaN,NaN,"Martin, George R.R.",NaN
37291,0007477155,DE,A Game of Thrones: The Story Continues. 7 Volu...,62.99,Harper Collins Publ. UK,NaN,NaN,NaN,NaN,"Martin, George R. R.",NaN
1495742,0007477155,FR,A Song of Ice and Fire,67.81,Brand: Harper Voyager,NaN,NaN,NaN,NaN,"Martin, George R.R.",NaN
1329558,0007477155,UK,A Song of Ice and Fire,48.30,HarperCollins Publishers,NaN,NaN,NaN,NaN,George R.R. Martin,NaN
...,...,...,...,...,...,...,...,...,...,...,...
115417,B0BL1YWQ11,DE,New Weight Watchers Freestyle Сооkbook: Fast &...,9.99,NaN,NaN,NaN,NaN,NaN,"Burris, Richard L.",NaN
461120,B0BL6ZWH18,DE,"1200Mbit/s WLAN Repeater, WLAN Verstaerker Dua...",42.99,GUHUASHI,white,NaN,NaN,NaN,NaN,✅【Einfache Installation】 Die übersichtliche un...
1440082,B0BL6ZWH18,ES,"Repetidor WiFi 1200Mbps, Amplificador Señal Wi...",42.99,GUHUASHI,white,NaN,NaN,NaN,NaN,✅ 【Instalación simple】 La interfaz de usuario ...
1395685,B0BL767T91,UK,Rainbow High 578314EUC Jewel Richie-Emerald Gr...,35.98,MGA Entertainment,NaN,NaN,578314,Glass,NaN,AN INCLUSIVE SELECTION OF DOLLS: The Rainbow H...
157117,B0BL767T91,DE,Rainbow High 578314EUC Jewel Richie-Smaragdgrü...,51.98,MGA Entertainment,NaN,NaN,578314,NaN,NaN,"Dies ist eine integrative Puppe, deren Charakt..."

In [9]:
# Keep only locale = 'UK' for simplicity

df_UK = df[df['locale'] == 'UK']
df_UK[df_UK.duplicated(subset=['id'], keep=False)].sort_values(by='id')

Empty DataFrame
Columns: [id, locale, title, price, brand, color, size, model, material, author, desc]
Index: []

In [11]:
df_UK.shape

(500180, 11)

In [12]:
df_UK['id'].nunique()

500180

In [13]:
# Save the cleaned data
# df_UK.to_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/products_train_UK.csv', index=False)

In [17]:
df_UK

,id,locale,title,price,brand,color,size,model,material,author,desc
0,B087LZNPHS,UK,"SOCHOW Sherpa Fleece Throw Blanket, Double-Sid...",24.99,SOCHOW,Teal Green,127cm×150cm,NaN,100% Polyester,NaN,COLOR: The sherpa throw blanket is available i...
1,B08THFN1KX,UK,Hippowarehouse Personalised Photo Printed Mous...,9.95,Hippowarehouse,White,240mm x 190mm x 60mm,50245-Mat-Perso,Rubber,NaN,Competitively priced
2,0804185328,UK,"500 Easy Recipes for Every Machine, Both Stove...",16.49,Clarkson Potter,White,NaN,NaN,NaN,"Scarbrough, Mark",NaN
3,B09VBKDBW6,UK,"TYHJOY Mini Bag Sealer, Handheld Vacuum Heat S...",11.99,TYHJOY,Black,NaN,FBA-sealer-black,Acrylonitrile Butadiene Styrene,NaN,【AFTER-SALE】This handheld food heat sealer sho...
4,B096ZW8B49,UK,Lucosobie Steering Wheel Lock - Car Anti-Theft...,26.99,Lucosobie,Black,NaN,NaN,Alloy Steel,NaN,🔐【 Anti-Friction & Customer First】Each box of ...
...,...,...,...,...,...,...,...,...,...,...,...
500175,B08D7KW8VK,UK,TOMHOUSEE Anime Cosplay Short Straight Hair Wi...,9.99,TOMHOUSEE,Deep Grey Yuki,NaN,NaN,Synthetic,NaN,NaN
500176,B073WXLXR9,UK,Crystals NEW brilliant ink twister bingo dabbe...,8.99,CRYSTALS,"Orange,blue,green,pink,red,purple",NaN,NaN,Plastic,NaN,NaN
500177,1529393833,UK,"Before I Do: the new, funny and unexpected lov...",4.50,Hodder Paperbacks,NaN,NaN,NaN,NaN,"Cousens, Sophie",NaN
500178,B0B3TJ1NDN,UK,"Black iPhone Charger Cable, iPhone Charger Bra...",4.49,AA-TECH,Black,2M,brd-ip-black-2022,Nylon Braided,NaN,Added Protection: An additional layer of prote...
500179,B00HUBEG3Y,UK,"Kids B Crafty 100 Mini Pegs, Mini Wooden Pegs,...",3.99,Kids B Crafty,NaN,NaN,NaN,Alloy Steel,NaN,"🔵 Mini Pegs : 100 Wooden Pegs For Decoration, ..."

In [18]:
df_UK = df_UK.fillna('')

df_UK['description'] = (
    'title: ' + df_UK['title'] +
    '\nbrand: ' + df_UK['brand'] +
    '\ncolor: ' + df_UK['color'] +
    '\nsize: ' + df_UK['size'] +
    '\nmodel: ' + df_UK['model'] +
    '\nmaterial: ' + df_UK['material'] +
    '\nauthor: ' + df_UK['author'] +
    '\ndesc: ' + df_UK['desc']
)

df_UK = df_UK[['id', 'price', 'description']]
df_UK

                id  price                                        description
0       B087LZNPHS  24.99  title: SOCHOW Sherpa Fleece Throw Blanket, Dou...
1       B08THFN1KX   9.95  title: Hippowarehouse Personalised Photo Print...
2       0804185328  16.49  title: 500 Easy Recipes for Every Machine, Bot...
3       B09VBKDBW6  11.99  title: TYHJOY Mini Bag Sealer, Handheld Vacuum...
4       B096ZW8B49  26.99  title: Lucosobie Steering Wheel Lock - Car Ant...
...            ...    ...                                                ...
500175  B08D7KW8VK   9.99  title: TOMHOUSEE Anime Cosplay Short Straight ...
500176  B073WXLXR9   8.99  title: Crystals NEW brilliant ink twister bing...
500177  1529393833   4.50  title: Before I Do: the new, funny and unexpec...
500178  B0B3TJ1NDN   4.49  title: Black iPhone Charger Cable, iPhone Char...
500179  B00HUBEG3Y   3.99  title: Kids B Crafty 100 Mini Pegs, Mini Woode...

[500180 rows x 3 columns]

In [20]:
print(df_UK['description'][0])

title: SOCHOW Sherpa Fleece Throw Blanket, Double-Sided Super Soft Luxurious Plush Blanket 127cm×150cm, Teal Green
brand: SOCHOW
color: Teal Green
size: 127cm×150cm
model:
material: 100% Polyester
author:
desc: COLOR: The sherpa throw blanket is available in a variety of colors, being able to meet your individual requirements. With different colors to choose from, you will easily find the suitable throw blanket to coordinate with your decor.

## dataset: sessions_train, for simplicity, only keep locale = 'UK' and items appears more than 20 times

In [96]:
sessions_train = pd.read_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/sessions_train.csv')

In [97]:
sessions_train

                                                prev_items   next_item locale
0                              ['B09W9FND7K' 'B09JSPLN1M']  B09M7GY217     DE
1        ['B076THCGSG' 'B007MO8IME' 'B08MF65MLV' 'B001B...  B001B4THSA     DE
2        ['B0B1LGXWDS' 'B00AZYORS2' 'B0B1LGXWDS' 'B00AZ...  B0767DTG2Q     DE
3        ['B09XMTWDVT' 'B0B4MZZ8MB' 'B0B7HZ2GWX' 'B09XM...  B0B4R9NN4B     DE
4                 ['B09Y5CSL3T' 'B09Y5DPTXN' 'B09FKD61R8']  B0BGVBKWGZ     DE
...                                                    ...         ...    ...
3606244           ['B086CYFSKW' 'B0874F9859' 'B086CYFSKW']  B07B5TYD76     IT
3606245                        ['B09NRZKZ7V' 'B08WJTPV93']  B08L1P4C3D     IT
3606246                        ['B085JFX7MP' 'B085JGHW8R']  B01MPWVD44     IT
3606247                        ['B00B0UING2' 'B00B0UING2']  B00D3HYEZ4     IT
3606248  ['B092S9D1SD' 'B09XQQ1S72' 'B0852MS7QC' 'B0B1V...  B0B7RX65YP     IT

[3606249 rows x 3 columns]

In [98]:
sessions_train_UK = sessions_train[sessions_train['locale'] == 'UK']

In [99]:
sessions_train_UK.shape

(1182181, 3)

In [20]:
from collections import Counter
import re

# First, let's concatenate prev_items and next_item into a single list
all_items = []
for index, row in sessions_train_UK.iterrows():
    # Use regular expression to match all alphanumeric sequences
    prev_items_list = re.findall(r"'([^']*)'", row['prev_items'])

    # Combine with the next_item
    combined_items = prev_items_list + [row['next_item']]
    all_items.extend(combined_items)

# Count the frequency of each item ID
item_counter = Counter(all_items)

In [23]:
# Extract items that appear several times
# HERE I SET THE THRESHOLD TO 20
items_with_multiple_occurrences = [item for item, count in item_counter.items() if count > 100]

In [100]:
len(items_with_multiple_occurrences)

6690

In [101]:
# Now, filter the DataFrame to only keep rows where 'next_item' is in 'items_with_multiple_occurrences'
sessions_train_UK_filtered = sessions_train_UK[sessions_train_UK['next_item'].isin(items_with_multiple_occurrences)]
sessions_train_UK_filtered.shape

(126876, 3)

In [102]:
sessions_train_UK_filtered.drop('locale', axis=1, inplace=True)

/var/folders/qx/wt3y86vj50sg2s6pkc5y62l00000gn/T/ipykernel_6916/3440340057.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sessions_train_UK_filtered.drop('locale', axis=1, inplace=True)

In [103]:
sessions_train_UK_filtered

                                                prev_items   next_item
2090544           ['B0845XT59N' 'B00474K8SY' 'B008BZVCVM']  B082VDS3YH
2090562                        ['B07ZMY8YDX' 'B09PFYM1CR']  B07V8H9HR6
2090569           ['B01D58042W' 'B01D58042W' 'B09T8DJ4RS']  B09JFSJVTQ
2090581                        ['B08VJ2VH2J' 'B08VJ2VH2J']  B08YK398Y5
2090615  ['B06VVQ35M2' 'B01NBMYWIN' 'B01NCPFGQ3' 'B01N0...  B0046U4CGS
...                                                    ...         ...
3272609  ['B0755GVMGD' 'B0755FP3XJ' 'B07Q59FLT1' 'B0755...  B0BD96VGPW
3272613           ['B07DYBV29C' 'B07R3FRRLG' 'B07DYBV29C']  B07S6C1DZ6
3272621           ['B01EJKXGXE' 'B0B36FCFYK' 'B097F9WDFJ']  B0971KDBHF
3272624                        ['B07YX4N2YV' 'B09TL5QNDT']  B09TL5N864
3272665  ['B09J1ZL3W8' 'B004UL7D82' 'B09G3JPTJQ' 'B09GV...  B07QPJS5BV

[126876 rows x 2 columns]

In [104]:
sessions_train_UK_filtered.to_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/sessions_train_UK_filtered.csv', index=False)

In [106]:
# Initialize an empty list to store the filtered prev_items
filtered_prev_items = []

# Loop over each row in the DataFrame
for index, row in sessions_train_UK_filtered.iterrows():
    # Use regular expression to match all alphanumeric sequences
    prev_items_list = re.findall(r"'([^']*)'", row['prev_items'])

    # Remove items not in items_with_multiple_occurrences
    filtered_list = [item for item in prev_items_list if item in items_with_multiple_occurrences]
    
    # Append the filtered list to the accumulator list
    filtered_prev_items.append(filtered_list)

In [107]:
# Assign the filtered lists to a new column in the DataFrame
sessions_train_UK_filtered['pre_items_filter'] = filtered_prev_items

/var/folders/qx/wt3y86vj50sg2s6pkc5y62l00000gn/T/ipykernel_6916/1936191246.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sessions_train_UK_filtered['pre_items_filter'] = filtered_prev_items

In [108]:
sessions_train_UK_filtered

,prev_items,next_item,pre_items_filter
2090544,['B0845XT59N' 'B00474K8SY' 'B008BZVCVM'],B082VDS3YH,[B0845XT59N]
2090562,['B07ZMY8YDX' 'B09PFYM1CR'],B07V8H9HR6,[]
2090569,['B01D58042W' 'B01D58042W' 'B09T8DJ4RS'],B09JFSJVTQ,[B09T8DJ4RS]
2090581,['B08VJ2VH2J' 'B08VJ2VH2J'],B08YK398Y5,[]
2090615,['B06VVQ35M2' 'B01NBMYWIN' 'B01NCPFGQ3' 'B01N0...,B0046U4CGS,"[B06VVQ35M2, B01NBMYWIN, B01NCPFGQ3, B01N0U5UDH]"
...,...,...,...
3272609,['B0755GVMGD' 'B0755FP3XJ' 'B07Q59FLT1' 'B0755...,B0BD96VGPW,"[B08L6RD61H, B07XTNBQ8G]"
3272613,['B07DYBV29C' 'B07R3FRRLG' 'B07DYBV29C'],B07S6C1DZ6,"[B07DYBV29C, B07DYBV29C]"
3272621,['B01EJKXGXE' 'B0B36FCFYK' 'B097F9WDFJ'],B0971KDBHF,[B097F9WDFJ]
3272624,['B07YX4N2YV' 'B09TL5QNDT'],B09TL5N864,[]
3272665,['B09J1ZL3W8' 'B004UL7D82' 'B09G3JPTJQ' 'B09GV...,B07QPJS5BV,[B09J1ZL3W8]

In [109]:
sessions_train_UK_filtered.drop('prev_items', axis=1, inplace=True)
sessions_train_UK_filtered.rename(columns={'pre_items_filter': 'prev_items'}, inplace=True)

/var/folders/qx/wt3y86vj50sg2s6pkc5y62l00000gn/T/ipykernel_6916/444493682.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sessions_train_UK_filtered.drop('prev_items', axis=1, inplace=True)
/var/folders/qx/wt3y86vj50sg2s6pkc5y62l00000gn/T/ipykernel_6916/444493682.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sessions_train_UK_filtered.rename(columns={'pre_items_filter': 'prev_items'}, inplace=True)

In [110]:
sessions_train_UK_filtered

          next_item                                        prev_items
2090544  B082VDS3YH                                      [B0845XT59N]
2090562  B07V8H9HR6                                                []
2090569  B09JFSJVTQ                                      [B09T8DJ4RS]
2090581  B08YK398Y5                                                []
2090615  B0046U4CGS  [B06VVQ35M2, B01NBMYWIN, B01NCPFGQ3, B01N0U5UDH]
...             ...                                               ...
3272609  B0BD96VGPW                          [B08L6RD61H, B07XTNBQ8G]
3272613  B07S6C1DZ6                          [B07DYBV29C, B07DYBV29C]
3272621  B0971KDBHF                                      [B097F9WDFJ]
3272624  B09TL5N864                                                []
3272665  B07QPJS5BV                                      [B09J1ZL3W8]

[126876 rows x 2 columns]

In [111]:
sessions_train_UK_filtered.to_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/sessions_train_UK_filtered.csv', index=False)

In [112]:
# Check the mean length of the filtered prev_items
lengths= sessions_train_UK_filtered['prev_items'].str.len()
stats = lengths.describe()

# Display the statistics
print(stats)

count    126876.000000
mean          1.558238
std           1.978371
min           0.000000
25%           0.000000
50%           1.000000
75%           2.000000
max          50.000000
Name: prev_items, dtype: float64

In [84]:
lengths.value_counts()

prev_items
0     45609
1     29068
2     26584
3     11192
4      6241
5      3172
6      1757
7      1085
8       712
9       428
10      290
11      203
12      144
13      111
14       64
15       43
16       37
17       24
18       19
21       19
19       16
20       12
22       10
23        8
24        6
26        4
25        3
33        2
37        2
30        2
36        2
50        1
35        1
32        1
31        1
34        1
43        1
28        1
Name: count, dtype: int64

### Only keep the rows where the number of previous items purchased >= 2, if it's longer than 2, only keep the latest 2 items

In [116]:
sessions_train_UK_filtered_len2 = sessions_train_UK_filtered.copy()
sessions_train_UK_filtered_len2

          next_item                                        prev_items
2090544  B082VDS3YH                                      [B0845XT59N]
2090562  B07V8H9HR6                                                []
2090569  B09JFSJVTQ                                      [B09T8DJ4RS]
2090581  B08YK398Y5                                                []
2090615  B0046U4CGS  [B06VVQ35M2, B01NBMYWIN, B01NCPFGQ3, B01N0U5UDH]
...             ...                                               ...
3272609  B0BD96VGPW                          [B08L6RD61H, B07XTNBQ8G]
3272613  B07S6C1DZ6                          [B07DYBV29C, B07DYBV29C]
3272621  B0971KDBHF                                      [B097F9WDFJ]
3272624  B09TL5N864                                                []
3272665  B07QPJS5BV                                      [B09J1ZL3W8]

[126876 rows x 2 columns]

In [117]:
# Define a function to keep only the latest 2 items if the length is greater than 2
def keep_latest_two(items):
    if len(items) >= 2:
        return items[-2:]
    else:
        return items

# Apply the function to the 'prev_items' column
sessions_train_UK_filtered_len2['prev_items'] = sessions_train_UK_filtered_len2['prev_items'].apply(keep_latest_two)

In [118]:
sessions_train_UK_filtered_len2

          next_item                prev_items
2090544  B082VDS3YH              [B0845XT59N]
2090562  B07V8H9HR6                        []
2090569  B09JFSJVTQ              [B09T8DJ4RS]
2090581  B08YK398Y5                        []
2090615  B0046U4CGS  [B01NCPFGQ3, B01N0U5UDH]
...             ...                       ...
3272609  B0BD96VGPW  [B08L6RD61H, B07XTNBQ8G]
3272613  B07S6C1DZ6  [B07DYBV29C, B07DYBV29C]
3272621  B0971KDBHF              [B097F9WDFJ]
3272624  B09TL5N864                        []
3272665  B07QPJS5BV              [B09J1ZL3W8]

[126876 rows x 2 columns]

In [119]:
# Filter the DataFrame to only keep rows where the length of 'prev_items' is at least 2
sessions_train_UK_filtered_len2 = sessions_train_UK_filtered_len2[sessions_train_UK_filtered_len2['prev_items'].str.len() >= 2]
sessions_train_UK_filtered_len2.shape

(52199, 2)

In [120]:
sessions_train_UK_filtered_len2

          next_item                prev_items
2090615  B0046U4CGS  [B01NCPFGQ3, B01N0U5UDH]
2090657  B07QS8M6W4  [B08HLVKVWR, B00I874D4Q]
2090669  B094VMJK1G  [B094VLF9QV, B0B24Z4D3V]
2090679  B07YQ1XM6J  [B0177HKHQK, B01HQHGIBY]
2090729  B0B63T3HGD  [B09JXY17B6, B004PYD9QE]
...             ...                       ...
3272505  B0BKPXCVHZ  [B08B4T5ZWJ, B08B4T5ZWJ]
3272540  B08KS94WMW  [B0BG912PV7, B09Z8C64DT]
3272591  B004AVB4UK  [B0BCLGK9DD, B00VP2SSFG]
3272609  B0BD96VGPW  [B08L6RD61H, B07XTNBQ8G]
3272613  B07S6C1DZ6  [B07DYBV29C, B07DYBV29C]

[52199 rows x 2 columns]

In [121]:
sessions_train_UK_filtered_len2.to_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/sessions_UK_finalized_len2.csv', index=False)

### Only keep the rows where the number of previous items purchased >= 3, if it's longer than 3, only keep the latest 3 items

In [123]:
sessions_train_UK_filtered_len3 = sessions_train_UK_filtered.copy()
sessions_train_UK_filtered_len3

          next_item                                        prev_items
2090544  B082VDS3YH                                      [B0845XT59N]
2090562  B07V8H9HR6                                                []
2090569  B09JFSJVTQ                                      [B09T8DJ4RS]
2090581  B08YK398Y5                                                []
2090615  B0046U4CGS  [B06VVQ35M2, B01NBMYWIN, B01NCPFGQ3, B01N0U5UDH]
...             ...                                               ...
3272609  B0BD96VGPW                          [B08L6RD61H, B07XTNBQ8G]
3272613  B07S6C1DZ6                          [B07DYBV29C, B07DYBV29C]
3272621  B0971KDBHF                                      [B097F9WDFJ]
3272624  B09TL5N864                                                []
3272665  B07QPJS5BV                                      [B09J1ZL3W8]

[126876 rows x 2 columns]

In [124]:
# Define a function to keep only the latest 2 items if the length is greater than 2
def keep_latest_three(items):
    if len(items) >= 3:
        return items[-3:]
    else:
        return items

# Apply the function to the 'prev_items' column
sessions_train_UK_filtered_len3['prev_items'] = sessions_train_UK_filtered_len3['prev_items'].apply(keep_latest_three)

In [125]:
sessions_train_UK_filtered_len3

          next_item                            prev_items
2090544  B082VDS3YH                          [B0845XT59N]
2090562  B07V8H9HR6                                    []
2090569  B09JFSJVTQ                          [B09T8DJ4RS]
2090581  B08YK398Y5                                    []
2090615  B0046U4CGS  [B01NBMYWIN, B01NCPFGQ3, B01N0U5UDH]
...             ...                                   ...
3272609  B0BD96VGPW              [B08L6RD61H, B07XTNBQ8G]
3272613  B07S6C1DZ6              [B07DYBV29C, B07DYBV29C]
3272621  B0971KDBHF                          [B097F9WDFJ]
3272624  B09TL5N864                                    []
3272665  B07QPJS5BV                          [B09J1ZL3W8]

[126876 rows x 2 columns]

In [126]:
# Filter the DataFrame to only keep rows where the length of 'prev_items' is at least 3
sessions_train_UK_filtered_len3 = sessions_train_UK_filtered_len3[sessions_train_UK_filtered_len3['prev_items'].str.len() >= 3]
sessions_train_UK_filtered_len3.shape

(25615, 2)

In [127]:
sessions_train_UK_filtered_len3

          next_item                            prev_items
2090615  B0046U4CGS  [B01NBMYWIN, B01NCPFGQ3, B01N0U5UDH]
2090729  B0B63T3HGD  [B09RQDZDF7, B09JXY17B6, B004PYD9QE]
2090735  B08FRDSKK8  [B082DYJF52, B08TWZD1H4, B082DYJF52]
2090744  B007EA03UQ  [B079KJLDF2, B08J4H9RSW, B074RCV4HQ]
2090798  B0838CF4T4  [B07PNL5STG, B07PNL5STG, B08KXPF5NK]
...             ...                                   ...
3272443  B07XLSHWP5  [B09F9QX6HB, B09XTTMJ8F, B09XTGBVF6]
3272449  B07SWQTPDZ  [B09Q3MSNJ8, B09Q3MRZ14, B08VF94DSV]
3272505  B0BKPXCVHZ  [B095BN6W33, B08B4T5ZWJ, B08B4T5ZWJ]
3272540  B08KS94WMW  [B09Z8C64DT, B0BG912PV7, B09Z8C64DT]
3272591  B004AVB4UK  [B00VP2SSFG, B0BCLGK9DD, B00VP2SSFG]

[25615 rows x 2 columns]

In [ ]:
sessions_train_UK_filtered_len3.to_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/sessions_UK_finalized_len3.csv', index=False)

          next_item                            prev_items
2090615  B0046U4CGS  [B01NBMYWIN, B01NCPFGQ3, B01N0U5UDH]
2090729  B0B63T3HGD  [B09RQDZDF7, B09JXY17B6, B004PYD9QE]
2090735  B08FRDSKK8  [B082DYJF52, B08TWZD1H4, B082DYJF52]
2090744  B007EA03UQ  [B079KJLDF2, B08J4H9RSW, B074RCV4HQ]
2090798  B0838CF4T4  [B07PNL5STG, B07PNL5STG, B08KXPF5NK]
...             ...                                   ...
3272443  B07XLSHWP5  [B09F9QX6HB, B09XTTMJ8F, B09XTGBVF6]
3272449  B07SWQTPDZ  [B09Q3MSNJ8, B09Q3MRZ14, B08VF94DSV]
3272505  B0BKPXCVHZ  [B095BN6W33, B08B4T5ZWJ, B08B4T5ZWJ]
3272540  B08KS94WMW  [B09Z8C64DT, B0BG912PV7, B09Z8C64DT]
3272591  B004AVB4UK  [B00VP2SSFG, B0BCLGK9DD, B00VP2SSFG]

[25615 rows x 2 columns]

### Filter out the items information that are not in the items_with_multiple_occurrences

In [42]:
df_UK = pd.read_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/products_train_UK_finalized.csv')

In [43]:
df_UK

               id  price                                        description
0      B09J5DBVDZ  22.95  title: GREEN HAVEN Premium Bioethanol Fuel – B...
1      B00004RFRU  28.75  title: Bialetti Moka Express Caffettiera in Al...
2      B09FT2FB75   8.99  title: 2Pack i-OS Phone Male Adapter to USB Ty...
3      B089X4XCLB  36.85  title: Marvel’s Spider-Man: Miles Morales – Pl...
4      B07PNBPVN1   3.75  title: Moon Creations Pro Face & Body Makeup |...
...           ...    ...                                                ...
64846  B08LZWC2MG  44.99  title: LIVIVO 4L Mini Fridge Cooler with Glass...
64847  B098BPC53X  12.37  title: Pawbits 1 Litre Scottish Salmon Oil For...
64848  B09RPMM568  12.99  title: Microwavable Wheat Bag | Heat Warmer Bo...
64849  B084R1YXKQ   1.60  title: Lindt EXCELLENCE Dark 90% Intense Cacao...
64850  B000EDWHZ4   8.90  title: Quality Pet Products Soft Washable Radi...

[64851 rows x 3 columns]

In [44]:
# filter out the products which are not in the list items_with_multiple_occurrences

df_UK_filtered = df_UK[df_UK['id'].isin(items_with_multiple_occurrences)]
df_UK_filtered.shape

(6690, 3)

In [45]:
df_UK_filtered.to_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/products_train_UK_finalized.csv', index=False)

In [46]:
df_UK_filtered

               id  price                                        description
4      B07PNBPVN1   3.75  title: Moon Creations Pro Face & Body Makeup |...
13     B0B45XQ6Q3   8.59  title: Car Phone Holder, Blukar Air Vent Car P...
21     B01CR9IRWY  16.00  title: Silentnight Anti-Allergy Pillows 2 Pack...
24     B077RCBS9C  36.98  title: GEMEK 2 Pack LED Camping Lantern, Survi...
45     B088BMDXPD   7.99  title: AMMIY Essential Oils Set of 6 x 10ml fo...
...           ...    ...                                                ...
64815  B00NBR70DO  13.22  title: Sony MDR-ZX110 Overhead Headphones - Bl...
64820  B08HYPQ4VR  12.99  title: Day of the Dead Headpiece Rose Floral C...
64827  B09LR8NRL9   2.89  title: Schwarzkopf Styling Keratin Hairspray, ...
64836  B0987DMWKW  15.99  title: Unicorn Light Up Letters, LED Letter Li...
64845  B08BHMLGSV  15.99  title: Beetles Gel Nail Polishes- Red Orange G...

[6690 rows x 3 columns]

In [48]:
df_UK_finalized = pd.read_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/products_train_UK_finalized.csv')

In [49]:
df_UK_finalized

              id  price                                        description
0     B07PNBPVN1   3.75  title: Moon Creations Pro Face & Body Makeup |...
1     B0B45XQ6Q3   8.59  title: Car Phone Holder, Blukar Air Vent Car P...
2     B01CR9IRWY  16.00  title: Silentnight Anti-Allergy Pillows 2 Pack...
3     B077RCBS9C  36.98  title: GEMEK 2 Pack LED Camping Lantern, Survi...
4     B088BMDXPD   7.99  title: AMMIY Essential Oils Set of 6 x 10ml fo...
...          ...    ...                                                ...
6685  B00NBR70DO  13.22  title: Sony MDR-ZX110 Overhead Headphones - Bl...
6686  B08HYPQ4VR  12.99  title: Day of the Dead Headpiece Rose Floral C...
6687  B09LR8NRL9   2.89  title: Schwarzkopf Styling Keratin Hairspray, ...
6688  B0987DMWKW  15.99  title: Unicorn Light Up Letters, LED Letter Li...
6689  B08BHMLGSV  15.99  title: Beetles Gel Nail Polishes- Red Orange G...

[6690 rows x 3 columns]

In [51]:
# Set the device to CPU
device = torch.device('cpu')

# Load the tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased').to(device)
model.eval()  # Put the model in evaluation mode

# Initialize the list to hold representations
representations = []

# Determine the number of chunks to process
total = len(df_UK_finalized)
chunk_size = 100  # Set this to something that fits in your memory
num_chunks = total // chunk_size + (1 if total % chunk_size != 0 else 0)

# Process the dataframe in chunks
for i in range(num_chunks):
    start_index = i * chunk_size
    end_index = start_index + chunk_size
    
    # Perform tokenization for the current chunk
    inputs = tokenizer(df_UK_finalized['description'].iloc[start_index:end_index].tolist(),
                       padding=True,
                       truncation=True,
                       max_length=512,
                       return_tensors="pt").to(device)
    
    # Forward pass to get embeddings
    with torch.no_grad():
        outputs = model(**inputs)
    
    # Extract the pooled output
    paragraph_representations = outputs.pooler_output.detach().cpu().numpy().tolist()
    representations.extend(paragraph_representations)
    
    # Display the progress
    print(f"Chunk {i+1}/{num_chunks} processed. ({(i+1)/num_chunks:.2%} complete)")

# After processing all chunks, add the representations to the dataframe
df_UK_finalized['representation'] = representations

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Chunk 1/67 processed. (1.49% complete)
Chunk 2/67 processed. (2.99% complete)
Chunk 3/67 processed. (4.48% complete)
Chunk 4/67 processed. (5.97% complete)
Chunk 5/67 processed. (7.46% complete)
Chunk 6/67 processed. (8.96% complete)
Chunk 7/67 processed. (10.45% complete)
Chunk 8/67 processed. (11.94% complete)
Chunk 9/67 processed. (13.43% complete)
Chunk 10/67 processed. (14.93% complete)
Chunk 11/67 processed. (16.42% complete)
Chunk 12/67 processed. (17.91% complete)
Chunk 13/67 processed. (19.40% complete)
Chunk 14/67 processed. (20.90% complete)
Chunk 15/67 processed. (22.39% complete)
Chunk 16/67 processed. (23.88% complete)
Chunk 17/67 processed. (25.37% complete)
Chunk 18/67 processed. (26.87% complete)
Chunk 19/67 processed. (28.36% complete)
Chunk 20/67 processed. (29.85% complete)
Chunk 21/67 processed. (31.34% complete)
Chunk 22/67 processed. (32.84% complete)
Chunk 23/67 processed. (34.33% complete)
Chunk 24/67 processed. (35.82% complete)
Chunk 25/67 processed. (37.31% complete)
Chunk 26/67 processed. (38.81% complete)
Chunk 27/67 processed. (40.30% complete)
Chunk 28/67 processed. (41.79% complete)
Chunk 29/67 processed. (43.28% complete)
Chunk 30/67 processed. (44.78% complete)
Chunk 31/67 processed. (46.27% complete)
Chunk 32/67 processed. (47.76% complete)
Chunk 33/67 processed. (49.25% complete)
Chunk 34/67 processed. (50.75% complete)
Chunk 35/67 processed. (52.24% complete)
Chunk 36/67 processed. (53.73% complete)
Chunk 37/67 processed. (55.22% complete)
Chunk 38/67 processed. (56.72% complete)
Chunk 39/67 processed. (58.21% complete)
Chunk 40/67 processed. (59.70% complete)
Chunk 41/67 processed. (61.19% complete)
Chunk 42/67 processed. (62.69% complete)
Chunk 43/67 processed. (64.18% complete)
Chunk 44/67 processed. (65.67% complete)
Chunk 45/67 processed. (67.16% complete)
Chunk 46/67 processed. (68.66% complete)
Chunk 47/67 processed. (70.15% complete)
Chunk 48/67 processed. (71.64% complete)
Chunk 49/67 processed. (73.13% complete)
Chunk 50/67 processed. (74.63% complete)
Chunk 51/67 processed. (76.12% complete)
Chunk 52/67 processed. (77.61% complete)
Chunk 53/67 processed. (79.10% complete)
Chunk 54/67 processed. (80.60% complete)
Chunk 55/67 processed. (82.09% complete)
Chunk 56/67 processed. (83.58% complete)
Chunk 57/67 processed. (85.07% complete)
Chunk 58/67 processed. (86.57% complete)
Chunk 59/67 processed. (88.06% complete)
Chunk 60/67 processed. (89.55% complete)
Chunk 61/67 processed. (91.04% complete)
Chunk 62/67 processed. (92.54% complete)
Chunk 63/67 processed. (94.03% complete)
Chunk 64/67 processed. (95.52% complete)
Chunk 65/67 processed. (97.01% complete)
Chunk 66/67 processed. (98.51% complete)
Chunk 67/67 processed. (100.00% complete)

In [53]:
df_UK_finalized

,id,price,description,representation
0,B07PNBPVN1,3.75,title: Moon Creations Pro Face & Body Makeup |...,"[-0.21872417628765106, -0.2500726580619812, -0..."
1,B0B45XQ6Q3,8.59,"title: Car Phone Holder, Blukar Air Vent Car P...","[-0.7130799889564514, -0.5445948839187622, -0...."
2,B01CR9IRWY,16.00,title: Silentnight Anti-Allergy Pillows 2 Pack...,"[-0.8353576064109802, -0.6093693375587463, -0...."
3,B077RCBS9C,36.98,"title: GEMEK 2 Pack LED Camping Lantern, Survi...","[-0.8522624969482422, -0.5257986783981323, -0...."
4,B088BMDXPD,7.99,title: AMMIY Essential Oils Set of 6 x 10ml fo...,"[-0.8538389205932617, -0.47541171312332153, -0..."
...,...,...,...,...
6685,B00NBR70DO,13.22,title: Sony MDR-ZX110 Overhead Headphones - Bl...,"[-0.9247933626174927, -0.5451830625534058, -0...."
6686,B08HYPQ4VR,12.99,title: Day of the Dead Headpiece Rose Floral C...,"[-0.9244785308837891, -0.5655009150505066, -0...."
6687,B09LR8NRL9,2.89,"title: Schwarzkopf Styling Keratin Hairspray, ...","[-0.8537996411323547, -0.557623565196991, -0.9..."
6688,B0987DMWKW,15.99,"title: Unicorn Light Up Letters, LED Letter Li...","[-0.6583928465843201, -0.3460875451564789, -0...."
6689,B08BHMLGSV,15.99,title: Beetles Gel Nail Polishes- Red Orange G...,"[-0.8860562443733215, -0.6518399715423584, -0...."

In [54]:
df_UK_representations = df_UK_finalized[['id', 'price', 'representation']]
df_UK_representations.to_csv('/Users/stoneman/Library/CloudStorage/OneDrive-Vanderbilt/Social_Network_Analysis/Amazon_Recommandation_Project/data/products_train_UK_representations.csv', index=False)

In [55]:
df_UK_representations

              id  price                                     representation
0     B07PNBPVN1   3.75  [-0.21872417628765106, -0.2500726580619812, -0...
1     B0B45XQ6Q3   8.59  [-0.7130799889564514, -0.5445948839187622, -0....
2     B01CR9IRWY  16.00  [-0.8353576064109802, -0.6093693375587463, -0....
3     B077RCBS9C  36.98  [-0.8522624969482422, -0.5257986783981323, -0....
4     B088BMDXPD   7.99  [-0.8538389205932617, -0.47541171312332153, -0...
...          ...    ...                                                ...
6685  B00NBR70DO  13.22  [-0.9247933626174927, -0.5451830625534058, -0....
6686  B08HYPQ4VR  12.99  [-0.9244785308837891, -0.5655009150505066, -0....
6687  B09LR8NRL9   2.89  [-0.8537996411323547, -0.557623565196991, -0.9...
6688  B0987DMWKW  15.99  [-0.6583928465843201, -0.3460875451564789, -0....
6689  B08BHMLGSV  15.99  [-0.8860562443733215, -0.6518399715423584, -0....

[6690 rows x 3 columns]